const { ADD_ADMIN, GET_SHOP, EDIT_SHOP } = require('./constants');

const ADMIN_PERMISSIONS = [GET_SHOP, ADD_ADMIN, EDIT_SHOP];
const EDITOR_PERMISSIONS = [GET_SHOP];

module.exports = { ADMIN_PERMISSIONS, EDITOR_PERMISSIONS };
